spring:
    application:
        name: myStudy
     #示例配置
    redis:
        port: 6379 #端口号
        password:  #输入redis数据库密码
        host:     #输入ip地址
        jedis:
            pool:
                max-idle: 6    #最大空闲数
                max-active: 10 #最大连接数
                min-idle: 2    #最小空闲数
        timeout: 2000   #连接超时


